package com.forbidad4tieba.hook.config

data class SettingsSnapshot(
    val areRestrictedFeaturesUnlocked: Boolean,
    val isAdBlockEnabled: Boolean,
    val isFeedAdBlockEnabled: Boolean,
    val isPostPageAdBlockEnabled: Boolean,
    val isForumPageAdBlockEnabled: Boolean,
    val isStrategyAdBlockEnabled: Boolean,
    val isSearchBoxTextAdBlockEnabled: Boolean,
    val isHomeTopBarAdBlockEnabled: Boolean,
    val isMineTabWebAdBlockEnabled: Boolean,
    val isHomeSideBarWebAdBlockEnabled: Boolean,
    val isHomeBottomEasterEggAdBlockEnabled: Boolean,
    val isHomeTopTabsCustomEnabled: Boolean,
    val isHomeTopTabMaterialEnabled: Boolean,
    val isHomeTopTabRecommendEnabled: Boolean,
    val isHomeTopTabLiveEnabled: Boolean,
    val isHomeTopTabFollowedEnabled: Boolean,
    val homeTopTabDisabledKeys: Set<String>,
    val isHomeTabAutoHideEnabled: Boolean,
    val isHomeTabRedDotHidden: Boolean,
    val isInputMemeBarHidden: Boolean,
    val isBottomTabsCustomEnabled: Boolean,
    val isBottomTabHomeEnabled: Boolean,
    val isBottomTabEnterForumEnabled: Boolean,
    val isBottomTabRetailStoreEnabled: Boolean,
    val isBottomTabMessageEnabled: Boolean,
    val isBottomTabMineEnabled: Boolean,
    val isBottomTabLiquidGlassEnabled: Boolean,
    val bottomTabLiquidGlass: BottomTabLiquidGlassConfig,
    val isEnterForumWebFilterEnabled: Boolean,
    val isOpenWebLinkInSystemBrowserEnabled: Boolean,
    val isHomeNativeGlassEnabled: Boolean,
    val isHomeTabDynamicTintEnabled: Boolean,
    val homeNativeGlassLightStyle: HomeGlassPreferences.HomeNativeGlassStyleConfig,
    val homeNativeGlassDarkStyle: HomeGlassPreferences.HomeNativeGlassStyleConfig,
    val isAutoRefreshDisabled: Boolean,
    val isPbGestureFontScaleDisabled: Boolean,
    val isAutoLoadMoreEnabled: Boolean,
    val isFreeCopyEnabled: Boolean,
    val isFreeCopyPostBodyEnabled: Boolean,
    val isFreeCopyPostLongPressEnabled: Boolean,
    val isFreeCopyCommentInjectionEnabled: Boolean,
    val isFreeCopyCommentDialogEnabled: Boolean,
    val isPbLikeAutoReplyEnabled: Boolean,
    val isCommentAvatarDirectProfileEnabled: Boolean,
    val pbLikeAutoReplyText: String,
    val isReplyVisibilityProbeEnabled: Boolean,
    val replyVisibilityProbeMaxAttempts: Int,
    val replyVisibilityProbeIntervalMs: Int,
    val isPbScrollCoalesceEnabled: Boolean,
    val isDefaultNotifyTabEnabled: Boolean,
    val simpleToggles: Set<SimpleToggle>,
    val isAutoSignInEnabled: Boolean,
    val isCleanShareTrackingParamsEnabled: Boolean,
    val isAiComponentsDisabled: Boolean,
    val isCustomPostFilterEnabled: Boolean,
    val isAdSdkComponentsDisabled: Boolean,
    val isVideoComponentsDisabled: Boolean,
    val isMonitorSyncComponentsDisabled: Boolean,
    val isPbPerformanceModeEnabled: Boolean,
    val isPerformanceOptimizationEnabled: Boolean,
    val isHostPerformanceFlagsForced: Boolean,
    val isPbPreloadForced: Boolean,
    val isHostSlideAnimationDisabled: Boolean,
    val isHostFeedColdOptEnabled: Boolean,
    val isApsarasScheduleDisabled: Boolean,
    val isFlutterPreinitDisabled: Boolean,
    val isLowEndDeviceConfigForced: Boolean,
    val isTitanPatchBlockEnabled: Boolean,
    val isPrivateReadReceiptInvisibleEnabled: Boolean,
    val isPostVoteFilterEnabled: Boolean,
    val isPostVideoFilterEnabled: Boolean,
    val isPostReplyFilterEnabled: Boolean,
    val isPostHotFilterEnabled: Boolean,
    val isPostGoodsFilterEnabled: Boolean,
    val isPostGameBookingFilterEnabled: Boolean,
    val isPostHelpFilterEnabled: Boolean,
    val isPostScoreFilterEnabled: Boolean,
    val isPostLotteryFilterEnabled: Boolean,
    val isPostLiveFilterEnabled: Boolean,
    val isPostRecommendForumFilterEnabled: Boolean,
    val isPostUnfollowedForumFilterEnabled: Boolean,
    val isPostForumKeywordFilterEnabled: Boolean,
    val postForumKeywordList: List<String>,
    val isPostModelScoreFilterEnabled: Boolean,
    val postModelScoreThresholds: List<ModelScoreSettings.ModelScoreThreshold>,
    val postModelScoreAutoPercentiles: Map<String, Int>,
    val postModelScoreStatsPostLimit: Int,
    val isDetailedLoggingEnabled: Boolean,
    val commentLevelFilter: CommentLevelFilterSettings,
) {
    companion object {
        /** Pre-initialization state; evaluated snapshots must supply every field explicitly. */
        internal fun bootstrap(): SettingsSnapshot = SettingsSnapshot(
            areRestrictedFeaturesUnlocked = false,
            isAdBlockEnabled = false,
            isFeedAdBlockEnabled = false,
            isPostPageAdBlockEnabled = false,
            isForumPageAdBlockEnabled = false,
            isStrategyAdBlockEnabled = false,
            isSearchBoxTextAdBlockEnabled = false,
            isHomeTopBarAdBlockEnabled = false,
            isMineTabWebAdBlockEnabled = false,
            isHomeSideBarWebAdBlockEnabled = false,
            isHomeBottomEasterEggAdBlockEnabled = false,
            isHomeTopTabsCustomEnabled = false,
            isHomeTopTabMaterialEnabled = true,
            isHomeTopTabRecommendEnabled = true,
            isHomeTopTabLiveEnabled = true,
            isHomeTopTabFollowedEnabled = true,
            homeTopTabDisabledKeys = emptySet(),
            isHomeTabAutoHideEnabled = false,
            isHomeTabRedDotHidden = false,
            isInputMemeBarHidden = false,
            isBottomTabsCustomEnabled = false,
            isBottomTabHomeEnabled = true,
            isBottomTabEnterForumEnabled = true,
            isBottomTabRetailStoreEnabled = true,
            isBottomTabMessageEnabled = true,
            isBottomTabMineEnabled = true,
            isBottomTabLiquidGlassEnabled = false,
            bottomTabLiquidGlass = BottomTabLiquidGlassConfig.DEFAULT,
            isEnterForumWebFilterEnabled = false,
            isOpenWebLinkInSystemBrowserEnabled = false,
            isHomeNativeGlassEnabled = false,
            isHomeTabDynamicTintEnabled = HomeGlassPreferences.DEFAULT_HOME_TAB_DYNAMIC_TINT_ENABLED,
            homeNativeGlassLightStyle = HomeGlassPreferences.HomeNativeGlassStyleConfig(),
            homeNativeGlassDarkStyle = HomeGlassPreferences.HomeNativeGlassStyleConfig(),
            isAutoRefreshDisabled = false,
            isPbGestureFontScaleDisabled = false,
            isAutoLoadMoreEnabled = false,
            isFreeCopyEnabled = true,
            isFreeCopyPostBodyEnabled = true,
            isFreeCopyPostLongPressEnabled = false,
            isFreeCopyCommentInjectionEnabled = true,
            isFreeCopyCommentDialogEnabled = true,
            isPbLikeAutoReplyEnabled = false,
            isCommentAvatarDirectProfileEnabled = false,
            pbLikeAutoReplyText = "",
            isReplyVisibilityProbeEnabled = false,
            replyVisibilityProbeMaxAttempts = ReplyPreferences.DEFAULT_REPLY_VISIBILITY_PROBE_MAX_ATTEMPTS,
            replyVisibilityProbeIntervalMs = ReplyPreferences.DEFAULT_REPLY_VISIBILITY_PROBE_INTERVAL_MS,
            isPbScrollCoalesceEnabled = false,
            isDefaultNotifyTabEnabled = true,
            simpleToggles = emptySet(),
            isAutoSignInEnabled = false,
            isCleanShareTrackingParamsEnabled = true,
            isAiComponentsDisabled = false,
            isCustomPostFilterEnabled = false,
            isAdSdkComponentsDisabled = false,
            isVideoComponentsDisabled = false,
            isMonitorSyncComponentsDisabled = false,
            isPbPerformanceModeEnabled = false,
            isPerformanceOptimizationEnabled = false,
            isHostPerformanceFlagsForced = false,
            isPbPreloadForced = false,
            isHostSlideAnimationDisabled = false,
            isHostFeedColdOptEnabled = false,
            isApsarasScheduleDisabled = false,
            isFlutterPreinitDisabled = false,
            isLowEndDeviceConfigForced = false,
            isTitanPatchBlockEnabled = false,
            isPrivateReadReceiptInvisibleEnabled = false,
            isPostVoteFilterEnabled = false,
            isPostVideoFilterEnabled = false,
            isPostReplyFilterEnabled = false,
            isPostHotFilterEnabled = false,
            isPostGoodsFilterEnabled = false,
            isPostGameBookingFilterEnabled = false,
            isPostHelpFilterEnabled = false,
            isPostScoreFilterEnabled = false,
            isPostLotteryFilterEnabled = false,
            isPostLiveFilterEnabled = false,
            isPostRecommendForumFilterEnabled = false,
            isPostUnfollowedForumFilterEnabled = false,
            isPostForumKeywordFilterEnabled = false,
            postForumKeywordList = emptyList(),
            isPostModelScoreFilterEnabled = false,
            postModelScoreThresholds = emptyList(),
            postModelScoreAutoPercentiles = emptyMap(),
            postModelScoreStatsPostLimit = ModelScoreSettings.DEFAULT_MODEL_SCORE_STATS_POST_LIMIT,
            isDetailedLoggingEnabled = false,
            commentLevelFilter = CommentLevelFilterSettings(false, CommentFilterPreferences.DEFAULT_MINIMUM_LEVEL, false, false),
        )
    }

    operator fun get(toggle: SimpleToggle): Boolean = toggle in simpleToggles

    internal val customPostRules: CustomPostFilterRules? = CustomPostFilterRules.from(this)

    fun isHomeNativeGlassRuntimeActive(): Boolean {
        return isHomeNativeGlassEnabled && hasAnyHomeNativeGlassBackgroundImage()
    }

    fun hasAnyHomeNativeGlassBackgroundImage(): Boolean {
        return homeNativeGlassLightStyle.hasBackgroundImage() ||
            homeNativeGlassDarkStyle.hasBackgroundImage()
    }

    fun homeNativeGlassStyleForDarkMode(darkMode: Boolean): HomeGlassPreferences.HomeNativeGlassStyleConfig {
        return if (darkMode) homeNativeGlassDarkStyle else homeNativeGlassLightStyle
    }

    fun shouldStabilizeHomeChrome(): Boolean {
        return isHomeTopBarAdBlockEnabled || isHomeNativeGlassRuntimeActive()
    }

}
