[versions]
agp = "9.2.1"
junit = "4.13.2"
json = "20240303"
dexkit = "2.2.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
json = { group = "org.json", name = "json", version.ref = "json" }
xposed-api = { group = "io.github.libxposed", name = "api", version = "102.0.0" }
dexkit = { group = "org.luckypray", name = "dexkit", version.ref = "dexkit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
